### ISSUE TITLE
Fix high vulnerabilities 

### ISSUE THREAD

**Issue by ClementVanPeuter** [Zenika/humeur-du-mois-2018#100]
We have many high severity vulnerabilities.
I try to fix them with updates of the relevant packages.
The relevant packages are related to the Firebase solution, like firebase-admin and Firestore client.

But these upgrades introduced breaking change:
See [here](https://github.com/firebase/firebase-admin-node/blob/master/CHANGELOG.md) and [here](https://github.com/googleapis/nodejs-firestore/blob/master/CHANGELOG.md)

**Comment by hgwood** [comment]
Here's the list of breaking changes:

- from upgrading from `firebase-admin` [v6 to v7](https://github.com/firebase/firebase-admin-node/blob/master/CHANGELOG.md#v700): 
  - app must be compatible with Firestore client v1 (aka `nodejs-firestore` see below) ❓ 

- from upgrading `nodejs-firestore` from [v0 to v1](https://github.com/googleapis/nodejs-firestore/blob/master/CHANGELOG.md#breaking-the-timestampsinsnapshots-default-has-changed-to-true)
  - app must not expect Dates out of Firestore queries ❓ 

- from upgrading from `firebase-admin` [v7 to v8](https://github.com/firebase/firebase-admin-node/blob/master/CHANGELOG.md#v800): 
  - app must run on Node.js 8: ✅  we are already running on this version, as set in `functions/package.json`, see [here](https://github.com/Zenika/humeur-du-mois-2018/blob/master/functions/package.json#L32) and [here](https://firebase.google.com/docs/functions/manage-functions#set_nodejs_version)
  - app must be compatible with Firestore client v2 (aka `nodejs-firestore` see below) ❓ 
 
- from upgrading `nodejs-firestore` from [v1 to v2](https://github.com/googleapis/nodejs-firestore/blob/master/CHANGELOG.md#-breaking-changes)
  - app must not use array arguments ❓ 
  - app must not use `getCollections` ✅

**Comment by hgwood** [comment]
Conclusion: upgrading to firebase-admin v8 should be safe. See #99.
