### ISSUE TITLE
Check if a user has already voted while checking if votes are opened

### ISSUE THREAD

**Issue by Ked57** [Zenika/humeur-du-mois-2018#130]
This was proposed in #129 . The point here is to help the user know if they already voted or not when arriving on the app instead of getting an error when voting

**Comment by Ked57** [comment]
So this is what I'm going to do

- [ ] Add a cloud function that takes an employee id and a campaign in parameter and checks if the employee already voted
- [ ] Run this cloud function in parallel to the `getCampaign`function so it does not make the page loading any longer than it already is
- [ ] Display a message that says the user already voted instead of the vote buttons if the user already voted

**Comment by hgwood** [comment]
This has been deployed
