### ISSUE TITLE
Don't send a reminder to people who already voted

### ISSUE THREAD

**Issue by Ked57** [Zenika/humeur-du-mois-2018#131]
Right now the reminder emails are sent to a mailing list (probably world@zenika.com), we should instead send them individualy to people who didn't vote yet

**Comment by Ked57** [comment]
I think the best way to do this is to use batch sending https://documentation.mailgun.com/en/latest/user_manual.html#batch-sending which is going to require minimal modifications

We need to adapt the sendReminders function to retrieve the list of users that haven't voted yet

What do you think @hgwood ?

**Comment by hgwood** [comment]
I don't think that's the simplest thing that'd solve the problem. I think the simplest solution is normal email with all recipients in the Cci field.

**Comment by hgwood** [comment]
This has been deployed.
