### ISSUE TITLE
📍 add Brest in agencies list

### ISSUE THREAD

**Issue by guillaumeLamanda** [Zenika/humeur-du-mois-2018#154]
Since 2019, Brest exists as an agency. Attached to Rennes, but still an agency. 

It would be great to be able to filter monthly mood on Brest agency. 🙂

I have not looked at the code, so I don't know if this information is linked to another data source or if it can be handled by the application.

Thanks for the work here 😘

**Comment by hgwood** [comment]
Hi Guillaume! Agencies are taken from Alibeez, which does not seem to be aware of the Brest agency. Sorry :(
