### ISSUE TITLE
Auth0 admins can identify who votes

### ISSUE THREAD

**Issue by hgwood** [Zenika/humeur-du-mois-2018#17]
# Problem

The id used to identity voters is in fact the Auth0 user ID. Auth0 admins can identify people from this ID through the Auth0 dashboard. Anonymity is compromised.

# Proposed solution

[Use Vault](https://github.com/hgwood/blog/blob/master/personal-secrets-in-vault/personal-secrets-in-vault.md) to store an opaque user id that can be used in Firestore.

**Comment by Ked57** [comment]
I've seen something else that needs to be addressed: there's data about the user in the local storage under the key "user".

You can clearly see the email, and the auth0 token.

**Comment by hgwood** [comment]
That's only about the currently logged in user, so it's not a problem is it?

**Comment by Ked57** [comment]
is it safe to leave it there ?

**Comment by hgwood** [comment]
Local storage is only accessible from the computer where the user logged in, that's considered safe.

**Comment by hgwood** [comment]
There is no anonymity right now anyway. See #5.
