### ISSUE TITLE
Remove employee import history

### ISSUE THREAD

**Issue by hgwood** [Zenika/humeur-du-mois-2018#28]
Currently, every time the employees are imported, the old import data is kept. This is not really necessary and makes the code for looking up the latest import complex.

- [x] Modify the import code to store employees in a `employees` top-level collection
- [x] Modify the security rules to authorize the front-end to read it
- [x] Modify the front-end to read from the new collection
- [x] Modify the cast vote function to read from the new collection and save all employees data into the vote
- [x] Modify the send email to manager code to read from the new collection

**Comment by Ked57** [comment]
Added in PR #33
