### ISSUE TITLE
Authenticated users can place votes for other people

### ISSUE THREAD

**Issue by hgwood** [Zenika/humeur-du-mois-2018#36]
`castVote` is callable through HTTP with a `{vote: string, voter: string}` payload. The function is protected using the authentication however the vote is recorded using the `voter` field found in the request payload. The payload could be forge to vote on the behalf of any employee.

Fix: change the `castVote` function to use the email address of the authenticated user instead of trusting the payload, then remove `voter` from the payload as it is no longer useful.

**Comment by Ked57** [comment]
Fixed by pull request #33
