### ISSUE TITLE
Bulk import votes

### ISSUE THREAD

**Issue by hgwood** [Zenika/humeur-du-mois-2018#38]
Create a new HTTP function that takes a JSON array of votes and inserts them into the database. The function should be protected by the admin key. Open question: should the payload be validated?

**Comment by Ked57** [comment]
Is it to be used for the migration of the old database ?

**Comment by hgwood** [comment]
Yes.

**Comment by Ked57** [comment]
Right now importing votes will trigger send email to manager. This is not intended.
We decided to modify castVote and the vote interface to have an optional field "vote_from_ui", and sendEmailToManager to check if that field exists so it doesn't send emails when importing votes
