### ISSUE TITLE
Allow voter to leave a message along with the mood

### ISSUE THREAD

**Issue by hgwood** [Zenika/humeur-du-mois-2018#43]
...and add it to the email to the manager.

Could be either before the vote (user has to enter the message in a text area that is on the same page as the mood buttons) or after (a new page that is shown after voting, while the vote is being recorded).

**Comment by Ked57** [comment]
It's been done and merge in #93

**Comment by hgwood** [comment]
Merged yes but was it deployed? I see only drafted releases.

**Comment by hgwood** [comment]
Looks like it was not deployed. Deploying now.
