### ISSUE TITLE
Add statistics by location

### ISSUE THREAD

**Issue by hgwood** [Zenika/humeur-du-mois-2018#45]
Following up on #11, add filters on the statistics page to see % of each mood for a location (agency).

**Comment by Ked57** [comment]
Cool ! Do we know how alibeez handles location agencies and technical agencies ? It might be a problem in the future

**Comment by hgwood** [comment]
Alibeez cleanly separates those concepts, don't worry :)

**Comment by Ked57** [comment]
We decided to make separate collections for the categories of statistics we want to show. Right now we have only one "stats" collection, we plan to have more based on:
* Agencies
* Years
* Keep the one we have with voting campaigns
* Type of position ? (Commercial, Manager, etc...)

**Comment by hgwood** [comment]
Done in #51
