### ISSUE TITLE
Serve Auth0 bundle from the app domain

### ISSUE THREAD

**Issue by lucsorel** [Zenika/humeur-du-mois-2018#80]
# Context
Mozilla Firefox for Linux Mint Quantum 64.0, 64 bits

After clicking on the Google screen to authenticate myself, the application freezes with different errors:

* an error in the developer console:

```
ReferenceError: auth0 is not defined[En savoir plus] main.js:1:7519 
<anonyme> https://humeur-du-mois-2018-prod.firebaseapp.com/main.js:1:7519 n https://humeur-du-mois-2018-prod.firebaseapp.com/main.js:1:105 
<anonyme> https://humeur-du-mois-2018-prod.firebaseapp.com/main.js:1:6800 n https://humeur-du-mois-2018-prod.firebaseapp.com/main.js:1:105 
<anonyme> https://humeur-du-mois-2018-prod.firebaseapp.com/main.js:1:6086 n https://humeur-du-mois-2018-prod.firebaseapp.com/main.js:1:105 
<anonyme> https://humeur-du-mois-2018-prod.firebaseapp.com/main.js:1:2414 n https://humeur-du-mois-2018-prod.firebaseapp.com/main.js:1:105 
<anonyme> https://humeur-du-mois-2018-prod.firebaseapp.com/main.js:1:902 
<anonyme> https://humeur-du-mois-2018-prod.firebaseapp.com/main.js:1:2 
```

* (a 404 for a png icon (see screenshot below))

![20190104-failed_when_authenticating](https://user-images.githubusercontent.com/3955251/51192663-5ab78780-18e7-11e9-8613-4910dcd0b6ea.jpg)

# Explanation

This is possibly caused by Mozilla Firefox protection against cross-site resource, this warning appears in the developer console:

```
Échec du chargement pour l’élément <script> dont la source est « https://cdn.auth0.com/js/auth0/9.7.3/auth0.min.js ».
```

**Comment by hgwood** [comment]
I did not manage to reproduce nor find documentation on this protection. Any pointers? Do you have any plugins installed?

**Comment by lucsorel** [comment]
sorry for the delay. Yes I have some plugins installed: the 3rd party https://cdn.auth0.com/js/auth0/9.7.3/auth0.min.js script was blocked by [Privacy badger](https://www.eff.org/privacybadger).

Therefore, this issue can follow 2 paths:
* include the auth0 script in the application artifacts (with webpack or similar) so that its code won't be considered as a 3rd party code
* reject the issue

**Comment by hgwood** [comment]
I understand why it blocks it and I'm OK with serving that file our-selves or include it in our bundle.

**Comment by hgwood** [comment]
I think this could as simple as changing the `externals` property of the webpack config.
