### ISSUE TITLE
Write a script to check config is ready for production

### ISSUE THREAD

**Issue by Ked57** [Zenika/humeur-du-mois-2018#81]
This nodejs script should check that the configuration is ready for production, this means

- [x] Emails are enabled
- [x] Collect stats is enabled
- [x] Import votes is disabled
- [x] Compute stats is disabled
- [x] Reminders are enabled
- [x] Emails to managers are enabled
- [x] Campaigns activated, start the 25th and end the 5th

**Comment by hgwood** [comment]
Closed by #82.
