### ISSUE TITLE
Change the title of the email

### ISSUE THREAD

**Issue by CallMeGoodWater** [Zenika/humeur-du-mois-2018#84]
Hi

Why don't you put directly the feeling in the title, so I don't need to open the message

The title "Antoine has shared how they feel" becomes "Antoine is feeling Great"

Thx

**Comment by hgwood** [comment]
Hi Antoine :)

Unfortunately this is not possible because email subjects are logged by email handling intermediaries, therefore putting the response of a user inside the email subject would break confidentiality.
